<?php

namespace backend\controllers;

use common\helper\HelperFunction;
use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use yii\web\Response;

/**
 * Site controller
 */
class SiteController extends BaseController
{


    public function unRequiredAuthAction()
    {
        return ['login', 'register']; // TODO: Change the autogenerated stub
    }

    public function requiredAuthAction()
    {
        return ['logout', 'index'];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }


    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $this->layout = 'blank';

        $model = new LoginForm();
        if (Yii::$app->request->isPost) {
            if ($model->load(Yii::$app->request->post()) && $model->login()) {
                return $this->goBack();
            }
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionRegister()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $model = new \backend\models\User();
        $secretCode = Yii::$app->request->get('code');
        if ($secretCode != YII_ADMIN_REGISTER_CODE) {
            return false;
        }
        if ($model->load(Yii::$app->request->get(), '') && $model->save()) {
            return true;
        }

        return HelperFunction::getFirstErrorModel($model);
    }
}

